// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqZ_Y2NATcPqd2da4ZUpuCoWpx-anwmIs',
    appId: '1:771263181839:web:0fa7a71701c71d37ec9f7a',
    messagingSenderId: '771263181839',
    projectId: 'flutter-location-01',
    authDomain: 'flutter-location-01.firebaseapp.com',
    storageBucket: 'flutter-location-01.firebasestorage.app',
    measurementId: 'G-CC1WYW2SFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSE1xDf-RNXUXqC5cH0htP0yjHfIS5tSk',
    appId: '1:771263181839:android:3722a9ca4571aac9ec9f7a',
    messagingSenderId: '771263181839',
    projectId: 'flutter-location-01',
    storageBucket: 'flutter-location-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsXKPWKNz1IuwDDwBYhfQgiSDErRYpo2k',
    appId: '1:771263181839:ios:4ca7085c71bea9efec9f7a',
    messagingSenderId: '771263181839',
    projectId: 'flutter-location-01',
    storageBucket: 'flutter-location-01.firebasestorage.app',
    iosBundleId: 'com.example.flutterSearchLocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsXKPWKNz1IuwDDwBYhfQgiSDErRYpo2k',
    appId: '1:771263181839:ios:4ca7085c71bea9efec9f7a',
    messagingSenderId: '771263181839',
    projectId: 'flutter-location-01',
    storageBucket: 'flutter-location-01.firebasestorage.app',
    iosBundleId: 'com.example.flutterSearchLocation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqZ_Y2NATcPqd2da4ZUpuCoWpx-anwmIs',
    appId: '1:771263181839:web:36f37f878209f354ec9f7a',
    messagingSenderId: '771263181839',
    projectId: 'flutter-location-01',
    authDomain: 'flutter-location-01.firebaseapp.com',
    storageBucket: 'flutter-location-01.firebasestorage.app',
    measurementId: 'G-5L5J692LGG',
  );
}
